### PR TITLE
update webpack

### PR DESCRIPTION
**Pull request by scytacki**
I wasn't able to run the dev server with node 12 or node 13.
I found that webpack needed to be updated to get it to work which triggered several changes. I wasn't meticulous about this though.

I didn't update babel, maybe I should have?

I checked most of the demos locally and they worked after this update.
If you have experience with doing a webpack 3 to 4 update then you might be able to spot things I missed. If you don't have experience then maybe we shouldn't merge this since I didn't do it carefully.

### CODE REVIEW

**Comment by pjanik** [comment]
If it builds correctly and Node 12/13 issues are fixed, it seems good to me 👍

**Comment by scytacki** [comment]
I'm not sure it is working right. I tried using npm link to include it in another project (geocode branch: https://github.com/concord-consortium/geocode/tree/170626950-attempt-snapshot-fix) and when doing so I got an error about shutterbug.js not finding jQuery. But this branch of geocode does have jQuery a dependency of the project, and the earlier shutterbug.js version (1.1.0) was working. I'm going to use nvm to install an earlier node version and try to get the 1.1.0 version of shutterbug.js building and see if it has the same problem with npm link.

**Comment by pjanik** [comment]
Strange. It seems that `externals` config hasn't been changed in webpack v4 and it looks correct:
https://webpack.js.org/configuration/externals/
(jquery is defined as external)
`package.json` could specify peerDepenendecy: 
https://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html
but I don't think it changes anything in this case if jQuery is already installed in the GeoCode.

**Comment by scytacki** [comment]
Yeah I tried running it with node version 9 and got the same error. Then googling about the error I fount the solution of using `resolve: { symlinks: false }`

**Pull request merged**
