### PR TITLE
Fix dynamic stylesheets

### PR DESCRIPTION
**Pull request by scytacki**
This fixes dynamic style sheets.
Besides the test examples in this project I also tested this in Geode which was failing because of this.

However I have not re-tested after switching build to use --mode=production
That seems to have removed a lot of code from dist/shutterbug.js

### CODE REVIEW

**Comment by pjanik** [comment]
It looks good to me 👍 
re `--mode=production`, I've thought about it in the previous PR that was updating webpack. Not a big deal, but I guess it might be better to leave the unminified version actually or provide both, but use unminified as the default for NPM package. So the client application has a choice. It will minify the whole app anyway if it wants to (including dependencies), but it might not e.g. to have easier debugging in dev mode.

**Comment by scytacki** [comment]
Good point about mode=production. I changed it back.

I think the next step is to test this in several of our interactives to make sure the css change didn't break them. Since npm link is kind of pain. Perhaps it is best to release a beta or pre-release version of some kind. Then it is would be easier to check out each project, change the dependency, commit the branch, and then test within LARA (or customized) demo folder of shutterbug.

@pjanik I'm not familiar with doing npm pre-releases, are you?
I'd just not want it to be picked up by some automatic `npm install`

**Comment by scytacki** [comment]
Reading this: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420 I think I know what we should do. But that was from 2016...

**Comment by scytacki** [comment]
I published it as `1.3.0-pre.1` using `npm publish --tag=next`. 

And then afterward I saw there was a `1.1.0-beta` published under a beta tag. Doh. So now we are inconsistent. Sorry.

**Comment by pjanik** [comment]
I removed `beta` tag using `npm dist-tag rm shutterbug beta`.

**Comment by scytacki** [comment]
Here is a build of geocode that uses this pre-release to fix its snapshot: 
https://github.com/concord-consortium/geocode/blob/170626950-attempt-snapshot-fix/package.json

I'd like to make builds of Lab, seismic-explorer, tectonic-explorer, wildfires, and most of the other interactives in this activity, to make sure this change doesn't break them:
https://authoring.staging.concord.org/activities/762

**Pull request merged**
