### PR TITLE
New version that works with server based on Chrome Headless

### PR DESCRIPTION
**Pull request by pjanik**
I don't think it's possible to look at the diff. Probably it's better to browse the code.  Or look at the demo (I've already updated gh-pages):
http://concord-consortium.github.io/shutterbug.js/demo/index.html

Changes:
- works with new server based on Chrome Headless and AWS Lambda
- a few of client-side fixes that ensure that snapshot looks right (dimensions, CSS, etc.)
- new build system (brunch replaced with webpack)
- code cleaned up and refactored to use ES6 syntax
- I refactored all the examples, so they're consistent and look cleaner, also added a few new ones
- added handling of hdpi canvases and video elements

Note that it's enough to update Shutterbug JS lib only in top-level apps which take screenshots (e.g. LARA). We don't have to update all the iframe models (Lab, JSmol, AgentScript). I've made sure that iframe-iframe API is backward compatible. The main reason to update can be to handle HDPI canvases better (it was necessary for SeismicExplorer).

I think it works pretty reliable. E.g. I took 500 screenshots and there're no failures (I had some random fails at the beginning, but it's been fixed).

Also, this can be reviewed together with server-side tool:
https://github.com/concord-consortium/shutterbug-lambda
It's based on Chrome Lambda and deployed to AWS Lambda.

### CODE REVIEW

**Comment by scytacki** [comment]
This probably a minor issue but the second 'snapshot' button on this page doesn't work.
This is looking really awesome.

**Comment by scytacki** [comment]
Another problem I found was that the 3d view of seismic explorer is not working. It doesn't work for me even outside of the iframe, so I suspect either my GPU is broken, or there is bug in the 3d view of seismic explorer.

**Comment by pjanik** [comment]
> This probably a minor issue but the second 'snapshot' button on this page doesn't work

You mean one of the examples? Which one? Hopefully, it's just example page.

> Another problem I found was that the 3d view of seismic explorer is not working. It doesn't work for me even outside of the iframe

Right. That's just a bug in master branch of SeismicExplorer. I noticed that before and started working on it.

**Comment by scytacki** [comment]
Yeah it would help if I included the link:)   The second button on this page is one I was referring to: http://concord-consortium.github.io/shutterbug.js/demo/svg-example.html

**Comment by pjanik** [comment]
Thanks, it's fixed now.

**Comment by scytacki** [comment]
Looks great to me. I quickly read through the code and it makes sense to me.

**Comment by scytacki** [comment]
If you have a bit more time could you submit a PR to LARA that updates its version of shutterbug to this one?

**Comment by pjanik** [comment]
LARA PR: https://github.com/concord-consortium/lara/pull/267

**Pull request merged**
